### ISSUE TITLE
Error: KeyError: 'socketio'

### ISSUE THREAD

**Issue by tungtruong-lunex** [mistio/mist.io#396]
Hello,

I would be than happy to have a 'help' for this problem, let me know more about correct form to deploy my own Mist 
I have already installed mist.io follow guide.

Deployment:
./bin/supervisord
Url: http://127.0.0.1:8000: It not run. I don't know, we must config nginx for port 800 or not ?

So, i use other way. I run command: 
./bin/paster serve development.ini --reload
and Point browser to http://127.0.0.1:6543. But it have problem same below:

root@LuATL-63:/home/duynguyen/mist.io# ./bin/paster serve development.ini --reload
Starting subprocess with file monitor
2015-03-02 22:13:50,889 WARNI [mist.io.config][MainThread] No settings.py file found.
2015-03-02 22:13:50,972 WARNI [mist.io.celery_app][MainThread] No settings.py file found.
Starting server in PID 671.
serving on 0.0.0.0:6543 view at http://127.0.0.1:6543
2015-03-02 22:14:35,194 INFO  [paste.httpserver.ThreadPool][MainThread] kill_hung_threads status: 10 threads (0 working, 10 idle, 0 starting) ave time N/A, max time 0.00sec, killed 0 workers
2015-03-02 22:14:49,259 CRITI [mist.io.views][worker 6] Uncaught non-mist exception? WTF!
Traceback (most recent call last):
  File "/home/duynguyen/mist.io/eggs/pyramid-1.4-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/duynguyen/mist.io/eggs/pyramid-1.4-py2.7.egg/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/duynguyen/mist.io/eggs/pyramid-1.4-py2.7.egg/pyramid/config/views.py", line 345, in rendered_view
    result = view(context, request)
  File "/home/duynguyen/mist.io/eggs/pyramid-1.4-py2.7.egg/pyramid/config/views.py", line 491, in _requestonly_view
    response = view(request)
  File "/home/duynguyen/mist.io/src/mist/io/views.py", line 939, in socketio
    request=request)
  File "/home/duynguyen/mist.io/eggs/gevent_socketio-0.3.6-py2.7.egg/socketio/__init__.py", line 68, in socketio_manage
    socket = environ['socketio']
KeyError: 'socketio'

**Comment by mgogoulos** [comment]
Hello, apologies for late response, have missed that. Is it still a problem or is it solved for you? Can you start ./bin/supervisord and paste here the output of  
```
./bin/supervisorctl status
```

Also, var/log/*.log will contain useful logs that can help us debug this

**Comment by BeVoice** [comment]
Hello,
I have the same problem.

The output of ./bin/supervisorctl status looks like

<pre>
celery                           RUNNING   pid 1545, uptime 21:07:48
haproxy                          RUNNING   pid 1542, uptime 21:07:48
memcache                         RUNNING   pid 1547, uptime 21:07:48
rabbitmq                         RUNNING   pid 1799, uptime 21:07:24
socketio                         RUNNING   pid 17330, uptime 0:22:58
uwsgi                            RUNNING   pid 17289, uptime 0:24:39
</pre>

I restarted uwsgi and socketio shortly before.

Additionally, in the logs are a lot of entries like this one:
<pre>
[pid: 17640|app: 0|req: 1186/1870] 192.168.1.103 () {36 vars in 600 bytes} [Tue May 19 13:28:41 2015] GET /socket.io/1/?t=1432034935274 => generated 21 bytes in 1 msecs (HTTP/1.1 500) 2 headers in 98 bytes (1 switches on core 0)
2015-05-19 13:28:42,635 CRITICAL MainThread views - exception_handler_mist: Uncaught non-mist exception? WTF!
Traceback (most recent call last):
  File "/home/abc/mist.io/eggs/pyramid-1.4-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/abc/mist.io/eggs/pyramid-1.4-py2.7.egg/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/home/abc/mist.io/eggs/pyramid-1.4-py2.7.egg/pyramid/config/views.py", line 345, in rendered_view
    result = view(context, request)
  File "/home/abc/mist.io/eggs/pyramid-1.4-py2.7.egg/pyramid/config/views.py", line 491, in _requestonly_view
    response = view(request)
  File "/home/abc/mist.io/src/mist/io/views.py", line 995, in socketio
    request=request)
  File "/home/abc/mist.io/eggs/gevent_socketio-0.3.6-py2.7.egg/socketio/__init__.py", line 67, in socketio_manage
    socket = environ['socketio']
KeyError: 'socketio'
</pre>

**Comment by dimrozakis** [comment]
@BeVoice could you please try checking out haproxy_conf branch, restarting everything and let us know if the problem persists?

The issues with 'socketio' key errors has been known to happen occasionally. It seems that haproxy doesn't always forward http requests to uwsgi and websocket requests to socketio as it should. Hopefully the haproxy_conf branch fixes this. Please let us know if it works for you, and if so it will soon be merged to master.
