### ISSUE TITLE
Error while installing 1.0

### ISSUE THREAD

**Issue by nwsheppard** [mistio/mist.io#535]
I am getting this on a fresh install:

OS: Ubuntu 14.04 Server
branch: master

```
Running "requirejs:mistjs" (requirejs) task
{ [Error: Error: ENOENT, no such file or directory '/root/mist.io/src/mist/io/static/dist/jquery/jquery.js'
    at Error (native)
]
  originalError: 
   { [Error: ENOENT, no such file or directory '/root/mist.io/src/mist/io/static/dist/jquery/jquery.js']
     errno: -2,
     code: 'ENOENT',
     path: '/root/mist.io/src/mist/io/static/dist/jquery/jquery.js',
     syscall: 'open',
     fileName: '/root/mist.io/src/mist/io/static/dist/jquery/jquery.js' } }
While:
  Installing grunt.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/root/mist.io/local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/root/mist.io/local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/root/mist.io/local/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1407, in _call
    return f()
  File "/root/mist.io/eggs/collective.recipe.cmd-0.11-py2.7.egg/collective/recipe/cmd/__init__.py", line 56, in install
    self.execute()
  File "/root/mist.io/eggs/collective.recipe.cmd-0.11-py2.7.egg/collective/recipe/cmd/__init__.py", line 69, in execute
    run_commands(cmds, self.shell)
  File "/root/mist.io/eggs/collective.recipe.cmd-0.11-py2.7.egg/collective/recipe/cmd/__init__.py", line 39, in run_commands
    check_call('%s %s' % (shell, tmpfile), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/bin/bash /tmp/tmpTglNFj/run' returned non-zero exit status 1
```

This happens on multiple boxes, not just one installation.

**Comment by nwsheppard** [comment]
Well after running into this multiple times, I finally back tracked this to bower.  Don't run the install as root or with sudo or it will fail.

**Comment by mgogoulos** [comment]
Hi, indeed the buildout needs to be run as user, otherwise it will fail. We will make sure this is made more clear on the docs. 
Cheers
