### ISSUE TITLE
Installation not working under Ubuntu 14.04.3 

### ISSUE THREAD

**Issue by smitetierlist** [mistio/mist.io#552]
Fresh install of obuntu server 14

    # history
    sudo su -
    cd /tmp/
    apt-get install git python-dev build-essential git erlang erlang-nox
    git clone https://github.com/mistio/mist.io.git
    cd mist.io
    virtualenv --no-site-packages .
    ./bin/pip install ansible
    ./bin/python bootstrap.py
    ./bin/buildout -v

    # lsb_release -a
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 14.04.3 LTS
    Release:        14.04
    Codename:       trusty

> Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 2279, in main
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 389, in run
    self.easy_install(spec, not self.no_deps)
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 619, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 668, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 851, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1079, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1065, in run_setup
    run_setup(setup_script, args)
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/sandbox.py", line 240, in run_setup
    raise
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/sandbox.py", line 164, in save_modules
    saved_exc.resume()
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/sandbox.py", line 139, in resume
    compat.reraise(type, exc, self._tb)
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/sandbox.py", line 237, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/sandbox.py", line 267, in run
    return func()
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/sandbox.py", line 236, in runner
    _execfile(setup_script, ns)
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-rrYoot/Pillow-3.0.0/setup.py", line 767, in <module>

>  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 160, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/command/bdist_egg.py", line 146, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/mist.io/lib/python2.7/site-packages/setuptools/command/install_lib.py", line 10, in run
    self.build()
  File "/usr/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/tmp/easy_install-rrYoot/Pillow-3.0.0/setup.py", line 515, in build_extensions

> ValueError: --enable-jpeg requested but jpeg not found, aborting.
An error occurred when trying to install Pillow 3.0.0. Look above this message for any errors that were output by easy_install.
While:
  Installing cloudpy.
  Getting distribution for 'Pillow'.
Error: Couldn't install: Pillow 3.0.0

**Comment by mgogoulos** [comment]
Hi, 

the buildout has to be run as user, if you run it as root supervisord won't be able to start some of the services. 

Regarding the issue with Pillow, seems that an updated version of Pillow creates problems, so edit  buildout.cfg and pin the version of Pillow to 2.9.0

buildout.cfg, line 131 change

Pillow 
to 

Pillow=2.9.0

and rerun the buildout (as user!)

Regards

**Comment by smitetierlist** [comment]
> An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/lsc/bin/mist.io/eggs/zc.buildout-2.4.4-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/home/lsc/bin/mist.io/eggs/zc.buildout-2.4.4-py2.7.egg/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/lsc/bin/mist.io/eggs/zc.buildout-2.4.4-py2.7.egg/zc/buildout/buildout.py", line 1407, in _call
    return f()
  File "/home/lsc/bin/mist.io/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 126, in install
    reqs, ws = self.working_set()
  File "/home/lsc/bin/mist.io/eggs/zc.recipe.egg-2.0.3-py2.7.egg/zc/recipe/egg/egg.py", line 84, in working_set
    allow_hosts=self.allow_hosts)
  File "/home/lsc/bin/mist.io/eggs/zc.buildout-2.4.4-py2.7.egg/zc/buildout/easy_install.py", line 848, in install
    return installer.install(specs, working_set)
  File "/home/lsc/bin/mist.io/eggs/zc.buildout-2.4.4-py2.7.egg/zc/buildout/easy_install.py", line 626, in install
    for spec in specs]
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2986, in parse
    reqs = list(parse_requirements(s))
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2930, in parse_requirements
    "version spec")
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2895, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
RequirementParseError: Expected version spec in Pillow=2.9.0 at =2.9.0

**Comment by mgogoulos** [comment]
Ops my fault, 

Pillow==2.9.0

at that point of buildout it needs ==

Cheers

**Comment by smitetierlist** [comment]
Installation wents fine.

Before I start a new ticket: readme says

> Point your browser to http://127.0.0.1:8000 and you are ready to roll!

it's port 8888 tho - it seems this get changed while installation?

anyway - thanks for the fast help. Maybe you can still answer this in here: I'm absolutely new to kvm - what credentials do I need to log into the webinterfaces?

**Comment by smitetierlist** [comment]
installation went fine.

Do I need to have a mist.io account to use it? 

The chrome console throws a lot of 

 > Adding listener to main for event ...

and 

> Disconnected.  WebSocket connection broken

I changed the address to listen from localhost to 0.0.0.0 tho - it' just a headless server in my private network for testing purposes.

**Comment by mgogoulos** [comment]
this is merged to the master branch now, so closing
