### ISSUE TITLE
RHEL 7.1 - error during buildout

### ISSUE THREAD

**Issue by V3XATI0N** [mistio/mist.io#559]
Not sure what to make of all this...
```
[mistio@edg-splunk3-az-education2020-com mist.io]$ ./bin/buildout -v
Installing 'mr.developer'.
We have no distributions for mr.developer that satisfies 'mr.developer'.
Getting distribution for 'mr.developer'.
Running easy_install:
"/home/mistio/src/mist.io/bin/python" "-c" "import sys; sys.path[0:0] = ['/home/mistio/src/mist.io/eggs/setuptools-18.4-py2.7.egg']; from setuptools.command.easy_install import main; main()" "-mZUNxd" "/home/mistio/src/mist.io/eggs/tmpGeTuH_" "-q" "/tmp/tmpkSqnbRget_dist/mr.developer-1.34.zip"
path=/home/mistio/src/mist.io/eggs/setuptools-18.4-py2.7.egg

Got mr.developer 1.34.
Picked: mr.developer = 1.34
mr.developer: Queued 'deploy_collectd' for checkout.
mr.developer: Queued 'libcloud' for checkout.
mr.developer: Queued 'paramiko' for checkout.
mr.developer: Cloned 'deploy_collectd' with git.
mr.developer: Cloned 'paramiko' with git.
* master
  remotes/origin/1.10
  remotes/origin/1.11
  remotes/origin/1.12
  remotes/origin/1.13
  remotes/origin/1.14
  remotes/origin/1.15
  remotes/origin/1.8
  remotes/origin/1.9
  remotes/origin/216-int
  remotes/origin/HEAD -> origin/master
  remotes/origin/ecdsa-known-hosts-keys-243
  remotes/origin/fix-proxycommand-infinite-loop-252
  remotes/origin/gateway-support
  remotes/origin/master
  remotes/origin/merge-ssh-fork-back-in
  remotes/origin/python3
  remotes/origin/sphinx-256
  remotes/origin/try-multiple-address-families-22
  remotes/origin/website-178

mr.developer: Cloned 'libcloud' with git.
Installing 'zc.buildout', 'setuptools'.
We have the best distribution that satisfies 'zc.buildout>=2.4.4'.
Picked: zc.buildout = 2.4.4
We have the best distribution that satisfies 'setuptools'.
Adding find link 'https://pypi.python.org/packages/source/c/certifi/certifi-2015.04.28.tar.gz#md5=12c7c3a063b2ff97a0f8291d8de41e8c' from setuptools 18.4
Adding find link 'https://pypi.python.org/packages/source/w/wincertstore/wincertstore-0.2.zip#md5=ae728f2f007185648d0c7a8679b361e2' from setuptools 18.4
Picked: setuptools = 18.4
Develop: '/home/mistio/src/mist.io/.'
Traceback (most recent call last):
  File "/tmp/tmpSaqroO", line 14, in <module>
    exec(compile(f.read(), '/home/mistio/src/mist.io/./setup.py', 'exec'))
  File "/home/mistio/src/mist.io/./setup.py", line 26, in <module>
    with open('test-requirements.txt') as f:
IOError: [Errno 2] No such file or directory: 'test-requirements.txt'
While:
  Installing.
  Processing develop directory '/home/mistio/src/mist.io/.'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/mistio/src/mist.io/eggs/zc.buildout-2.4.4-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/home/mistio/src/mist.io/eggs/zc.buildout-2.4.4-py2.7.egg/zc/buildout/buildout.py", line 528, in install
    installed_develop_eggs = self._develop()
  File "/home/mistio/src/mist.io/eggs/zc.buildout-2.4.4-py2.7.egg/zc/buildout/buildout.py", line 770, in _develop
    zc.buildout.easy_install.develop(setup, dest)
  File "/home/mistio/src/mist.io/eggs/zc.buildout-2.4.4-py2.7.egg/zc/buildout/easy_install.py", line 938, in develop
    call_subprocess(args)
  File "/home/mistio/src/mist.io/eggs/zc.buildout-2.4.4-py2.7.egg/zc/buildout/easy_install.py", line 159, in call_subprocess
    % repr(args)[1:-1])
Exception: Failed to run command:
'/home/mistio/src/mist.io/bin/python', '/tmp/tmpSaqroO', '-q', 'develop', '-mxN', '-d', '/home/mistio/src/mist.io/develop-eggs/tmpTaDNEtbuild'
```

**Comment by V3XATI0N** [comment]
Update --
This happened after using ./bin/pip install pyvmomi in order to support vSphere. This error occurs because the two folders "PyVmomi" and "PyVim" don't exist. Creating the folders manually allowed the buildout to complete, but I have not yet tested whether vSphere functions work.

**Comment by mgogoulos** [comment]
You are right, pyvmomi packaging seems to be broken and messes with files. If you git clone mist.io repository, create the virtualenv, and run ./bin/pip install pyvmomi it will mess 1-2 files, so git stash is needed in order for the buildout to be run. Thanks for noticing this!

**Comment by V3XATI0N** [comment]
Thanks. I wiped it out and started again from scratch, without pyvmomi. Now it installs and runs but trying to add a baremetal server I get "failed to add backend - service not running"

**Comment by mgogoulos** [comment]
check that all services are up and running with
```
./bin/supervisorctl status
```

if not a tail -f var/log/*.log might show what is the problem. Sometimes epmd is not running, so check it is running and if not start it with epmd -daemon.  If it can't start maybe some dependency is not installed (eg erlang).

**Comment by mgogoulos** [comment]
If the service is not working as expected, run an 
```
./bin/supervisorctl status
```

and see what service is not running (all should be running for mist.io to run well).
Also have a look on the logs

```
tail -f /home/mist/mist.io/var/log/*.log
```

if rabbitmq is not running (a usual suspect!) check that epmd is running, and if not start it with

```
epmd -daemon
```

All system dependencies should be installed, otherwise the installation won't be successful
