### ISSUE TITLE
Install fails on haproxy

### ISSUE THREAD

**Issue by manderso7** [mistio/mist.io#628]
I'm apparently unable to get to the haproxy site, either haproxy.1wt.eu or haproxy.org, and thus, the buildout script fails. Can someone suggest a workaround? I can install haproxy from another source and would need help in adjusting the installation script. Thanks.

**Comment by mgogoulos** [comment]
Hi, seems that haproxy.org is down indeed (don't know for how long but I would consider letting them know, just in case they are not aware of it).

I can expect it being up very soon, but just in case you'd like to experiment ... here are some steps: 

1) git clone mist.io and create a virtualenv and install ansible dependency, according to the installation docs
```
$git clone https://github.com/mistio/mist.io.git 
$cd mist.io
$virtualenv --no-site-packages .
$./bin/pip install ansible
```

2) remove haproxy from the buildout section of buildout.cfg (that is removing line 10 at the moment). 

3) run bootstrap.py and buildout 
```
$python bootstrap.py && ./bin/buildout -v
```

4) if this finishes without problems, you have to install haproxy via the system packages (or other way?). For example on Ubuntu/Debian that would be apt-get install haprpoxy -y

Almost there. Create a link to bin/haproxy. On my system this has been:
```
user@user:~mist.io$ which haproxy 
/usr/sbin/haproxy
user@user:~mist.io$ ln -s /usr/sbin/haproxy bin/haproxy 
```

5) start supervisord and make sure all services are up 
```
user@user:~mist.io$ ./bin/supervisorctl status
celery                           RUNNING   pid 24812, uptime 0:00:34
haproxy                          RUNNING   pid 24986, uptime 0:00:04
hub-shell                        RUNNING   pid 24814, uptime 0:00:34
memcache                         RUNNING   pid 24813, uptime 0:00:34
rabbitmq                         RUNNING   pid 24811, uptime 0:00:34
sockjs                           RUNNING   pid 24809, uptime 0:00:34
uwsgi                            RUNNING   pid 24810, uptime 0:00:34

```

Cheers,
Markos

**Comment by manderso7** [comment]
Yep, that got me farther, and I was able to complete the installation.However, now when I start, rabbitmq is "starting" and hub-shell has "EXITED". Rabbitmq's log tells me "  Crash dump was written to: erl_crash.dump
Kernel pid terminated (application_controller) ({application_start_failure,kernel,{{shutdown,{failed_to_start_child,net_sup,{shutdown,{failed_to_start_child,net_kernel,{'EXIT',nodistribution}}}}},{k" and hub-shell's log contains:
  No handlers could be found for logger "mist.io.config"
2015-11-27 17:57:21 INFO Dummy-1 main - __init__: HubServer 87113a2262244b56b611c9661997e8c7: Initializing.
2015-11-27 17:57:21 INFO Dummy-1 main - start: HubServer 87113a2262244b56b611c9661997e8c7: Starting.
Traceback (most recent call last):
  File "/home/manderso/mist.io/eggs/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/greenlet.py", line 327, in run
    result = self._run(*self.args, **self.kwargs)
  File "/home/manderso/mist.io/src/mist/io/hub/main.py", line 233, in amqp_consume
    self.chan.exchange_declare(self.exchange, 'topic')
  File "/home/manderso/mist.io/src/mist/io/hub/main.py", line 86, in chan
    conn = self.conn
  File "/home/manderso/mist.io/src/mist/io/hub/main.py", line 66, in conn
    self.conns[gid] = amqp.Connection(config.AMQP_URI)
  File "/home/manderso/mist.io/eggs/amqp-1.4.6-py2.7.egg/amqp/connection.py", line 165, in __init__
    self.transport = self.Transport(host, connect_timeout, ssl)
  File "/home/manderso/mist.io/eggs/amqp-1.4.6-py2.7.egg/amqp/connection.py", line 186, in Transport
    return create_transport(host, connect_timeout, ssl)
  File "/home/manderso/mist.io/eggs/amqp-1.4.6-py2.7.egg/amqp/transport.py", line 299, in create_transport
    return TCPTransport(host, connect_timeout)
  File "/home/manderso/mist.io/eggs/amqp-1.4.6-py2.7.egg/amqp/transport.py", line 95, in __init__
    raise socket.error(last_err)
error: [Errno 111] Connection refused
<Greenlet at 0x7f31ec038f50: <bound method HubServer.amqp_consume of <mist.io.hub.main.HubServer object at 0x7f31e638e610>>> failed with error

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/manderso/mist.io/eggs/ipython-4.0.1-py2.7.egg/IPython/core/history.py", line 816, in stop
    self.join()
  File "/usr/lib/python2.7/threading.py", line 949, in join
    self.__block.wait()
  File "/usr/lib/python2.7/threading.py", line 339, in wait
    waiter.acquire()
  File "gevent/_semaphore.pyx", line 112, in gevent._semaphore.Semaphore.acquire (gevent/gevent._semaphore.c:3386)
  File "/home/manderso/mist.io/eggs/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/hub.py", line 338, in switch
    return greenlet.switch(self)
LoopExit: This operation would block forever
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/manderso/mist.io/eggs/ipython-4.0.1-py2.7.egg/IPython/core/history.py", line 816, in stop
    self.join()
  File "/usr/lib/python2.7/threading.py", line 949, in join
    self.__block.wait()
  File "/usr/lib/python2.7/threading.py", line 339, in wait
    waiter.acquire()
  File "gevent/_semaphore.pyx", line 112, in gevent._semaphore.Semaphore.acquire (gevent/gevent._semaphore.c:3386)
  File "/home/manderso/mist.io/eggs/gevent-1.0.2-py2.7-linux-x86_64.egg/gevent/hub.py", line 338, in switch
    return greenlet.switch(self)
gevent.hub.LoopExit: This operation would block forever

**Comment by mgogoulos** [comment]
make sure epmd is running. ps aux|grep epmd
If it is not running, then start it with 
```
user@user:~$ epmd -daemon
```

and then restart the two services
```
./bin/supervisorctl restart rabbitmq hub-shell
```

this is a known issue with epmd and erlang

**Comment by manderso7** [comment]
yes sir that did the trick. How did I miss the epmd daemon, and how do I make sure that's running when mistio is supposed to be running?

**Comment by mgogoulos** [comment]
Hi, this is a known bug on some systems (Ubuntu/Debian) and erlang, we're trying to see how it can be addressed. If all supervisorctl services are RUNNING you don't have to worry. But if you start all services with ./bin/supervisord and after a few seconds check that rabbitmq and hub-shell are not started, you have to do the above - epmd -daemon &&  ./bin/supervisorctl restart rabbitmq hub-shell

Sorry for the trouble

**Comment by cpsaltis** [comment]
What problem are you looking to solve with Mist.io @manderso7?

**Comment by manderso7** [comment]
Trying to get a web front end to manage a kvm homelab.

**Comment by agentkgb** [comment]
A note for you devs, the url for haproxy src has been changed, so after changing it in buildout.cfg it works. The correct url: http://www.haproxy.org/download/1.5/src/... instead of the included *.1wt.eu url.
Still working on getting mist.io up and running.

**Comment by mgogoulos** [comment]
Hi @agentkgb , thanks for the link. The url for haproxy that is contained on buildout.cfg file (http://haproxy.1wt.eu/download/1.5/src/haproxy-1.5.14.tar.gz) is working now, we might replace it with the haproxy.org url however if this is now a more stable url/domain.

Cheers
