### ISSUE TITLE
buildout fail

### ISSUE THREAD

**Issue by mcrypt** [mistio/mist.io#640]
Ubuntu 14.04.3

git clone https://github.com/mistio/mist.io.git 
cd mist.io 
virtualenv --no-site-packages . 
./bin/pip install ansible 
./bin/python bootstrap.py 
./bin/buildout -v

Running "requirejs:mistjs" (requirejs) task
/tmp/tmpLlvG1H/run: line 1: 10261 Killed                  ./bin/grunt --force
While:
  Installing grunt.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/user/mist.io/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1992, in main

    getattr(buildout, command)(args)
  File "/home/user/mist.io/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/user/mist.io/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1407, in _call
    return f()
  File "/home/user/mist.io/eggs/collective.recipe.cmd-0.11-py2.7.egg/collective/recipe/cmd/__init__.py", line 56, in install
    self.execute()
  File "/home/user/mist.io/eggs/collective.recipe.cmd-0.11-py2.7.egg/collective/recipe/cmd/__init__.py", line 69, in execute
    run_commands(cmds, self.shell)
  File "/home/user/mist.io/eggs/collective.recipe.cmd-0.11-py2.7.egg/collective/recipe/cmd/__init__.py", line 39, in run_commands
    check_call('%s %s' % (shell, tmpfile), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/bin/bash /tmp/tmpLlvG1H/run' returned non-zero exit status 137

**Comment by mgogoulos** [comment]
Hi, 
I have just run the buildout on an ubuntu 14.04.03 server (1 cpu, 4G ram) and it has finished successfully. What are the specs for the server you're trying to run the buildout? On this line

```
Running "requirejs:mistjs" (requirejs) task
/tmp/tmpLlvG1H/run: line 1: 10261 Killed ./bin/grunt --force
While:
Installing grunt.

```

I see that the process has been killed by the OS. The grunt command is called from the buildout at some point and it is indeed RAM/cpu intensive for the few seconds it runs (installing js dependencies and minifying code), so this might be the reason it is killed by the system before it finishes, and thus the buildout process never succeeds.

**Comment by mcrypt** [comment]
Hi,
A lack of resources was indeed the problem.. added more cpu/ram and buildout runs as expected.
Thanks
