### ISSUE TITLE
celery fatal error

### ISSUE THREAD

**Issue by ShiveringBear** [mistio/mist.io#674]
I'm trying to run mist.io in a docker container on os x (Virtualbox) per the instructions here: http://docs.mist.io/article/39-installation.  

All services start except for celery.  socksjs exited without reporting an error.  

mist@e954f7f316d6:~/mist.io$ ./bin/supervisorctl status
celery                           FATAL     Exited too quickly (process log may have details)
haproxy                          RUNNING   pid 854, uptime 0:00:15
hub-shell                        RUNNING   pid 861, uptime 0:00:15
memcache                         RUNNING   pid 859, uptime 0:00:15
rabbitmq                         RUNNING   pid 857, uptime 0:00:15
sockjs                           EXITED    Jan 21 07:32 PM
uwsgi                            RUNNING   pid 856, uptime 0:00:15
mist@e954f7f316d6:~/mist.io$ 

The following is written over and over to the log: 

ImportError: No module named template
Traceback (most recent call last):
  File "/home/mist/mist.io/bin/celery", line 70, in <module>
    sys.exit(celery.__main__.main())
  File "/home/mist/mist.io/eggs/celery-3.1.17-py2.7.egg/celery/__main__.py", line 30, in main
    main()
  File "/home/mist/mist.io/eggs/celery-3.1.17-py2.7.egg/celery/bin/celery.py", line 81, in main
    cmd.execute_from_commandline(argv)
  File "/home/mist/mist.io/eggs/celery-3.1.17-py2.7.egg/celery/bin/celery.py", line 769, in execute_from_commandline
    super(CeleryCommand, self).execute_from_commandline(argv)))
  File "/home/mist/mist.io/eggs/celery-3.1.17-py2.7.egg/celery/bin/base.py", line 305, in execute_from_commandline
    argv = self.setup_app_from_commandline(argv)
  File "/home/mist/mist.io/eggs/celery-3.1.17-py2.7.egg/celery/bin/base.py", line 465, in setup_app_from_commandline
    self.app = self.find_app(app)
  File "/home/mist/mist.io/eggs/celery-3.1.17-py2.7.egg/celery/bin/base.py", line 485, in find_app
    return find_app(app, symbol_by_name=self.symbol_by_name)
  File "/home/mist/mist.io/eggs/celery-3.1.17-py2.7.egg/celery/app/utils.py", line 232, in find_app
    sym = imp(app)
  File "/home/mist/mist.io/eggs/celery-3.1.17-py2.7.egg/celery/utils/imports.py", line 101, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mist/mist.io/src/mist/io/tasks.py", line 25, in <module>
    import ansible.utils.template
ImportError: No module named template

**Comment by mgogoulos** [comment]
Hi, 
sorry for the trouble, the docker image that has been uploaded yesterday to docker registry contains a fault that prevents all services from starting correctly. We'll make sure tomorrow a new one is uploaded and I will update the ticket here. 

As a temp workaround you can run 

```
mist@e954f7f:~/mist.io$ ./bin/pip uninstall ansible
```
select yes, and then restart all services

```
mist@e954f7f:~/mist.io$ ./bin/supervisorctl restart all
```
and then 

```
mist@e954f7f:~/mist.io$ ./bin/supervisorctl status
```

should show all services as running. 

Cheers,
Markos

**Comment by ShiveringBear** [comment]
That did it!  I should have raised the issue sooner!  

Thanks for the quick turn-around!  

/bear

**Comment by mgogoulos** [comment]
Nice to read that! A new docker image has been uploaded so after updating it it should work without problems. 
Let us know if you have any requests, suggestions or if you find other issues. 

Cheers
