### ISSUE TITLE
error during buildout

### ISSUE THREAD

**Issue by yawboateng** [mistio/mist.io#716]
I keep getting this error during the grunt install of buildout (im running it as a user):

```
Installing grunt.
Running "emberTemplates:compile" (emberTemplates) task
File "dist/templates.js" created.

Running "symlink:dist" (symlink) task
Creating symlink to ../../../../dist/ at src/mist/io/static/dist...OK

Running "symlink:jquery" (symlink) task
Creating symlink to ../bower_components/jquery/dist/ at dist/jquery...OK

Running "symlink:jqm" (symlink) task
Creating symlink to ../bower_components/jquery-mobile-bower/ at dist/jqm...OK

Running "symlink:ember" (symlink) task
Creating symlink to ../bower_components/ember/ at dist/ember...OK

Running "symlink:requirejs" (symlink) task
Creating symlink to ../bower_components/requirejs/ at dist/requirejs...OK

Running "symlink:requirejs_text" (symlink) task
Creating symlink to ../bower_components/requirejs-text/ at dist/requirejs-text...OK

Running "symlink:sockjs" (symlink) task
Creating symlink to ../bower_components/sockjs-client/dist/ at dist/sockjs...OK

Running "symlink:md5" (symlink) task
Creating symlink to ../bower_components/md5/ at dist/md5...OK

Running "symlink:d3" (symlink) task
Creating symlink to ../bower_components/d3/ at dist/d3...OK

Running "symlink:c3" (symlink) task
Creating symlink to ../bower_components/c3/ at dist/c3...OK

Running "symlink:term" (symlink) task
Creating symlink to ../bower_components/term.js/ at dist/term.js...OK

Running "symlink:images" (symlink) task
Creating symlink to ../src/mist/io/static/images at dist/images...OK

Running "symlink:fonts" (symlink) task
Creating symlink to ../src/mist/io/static/fonts at dist/fonts...OK

Running "symlink:states" (symlink) task
Creating symlink to ../src/mist/io/static/states at dist/states...OK

Running "symlink:yamljs" (symlink) task
Creating symlink to ../node_modules/yamljs/ at dist/yamljs...OK

Running "requirejs:mistjs" (requirejs) task
/tmp/tmptP0K6H/run: line 1:  6585 Killed                  ./bin/grunt --force
While:
  Installing grunt.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/user/mist.io/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/home/user/mist.io/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 666, in install
    installed_files = self[part]._call(recipe.install)
  File "/home/user/mist.io/eggs/zc.buildout-2.5.0-py2.7.egg/zc/buildout/buildout.py", line 1407, in _call
    return f()
  File "/home/user/mist.io/eggs/collective.recipe.cmd-0.11-py2.7.egg/collective/recipe/cmd/__init__.py", line 56, in install
    self.execute()
  File "/home/user/mist.io/eggs/collective.recipe.cmd-0.11-py2.7.egg/collective/recipe/cmd/__init__.py", line 69, in execute
    run_commands(cmds, self.shell)
  File "/home/user/mist.io/eggs/collective.recipe.cmd-0.11-py2.7.egg/collective/recipe/cmd/__init__.py", line 39, in run_commands
    check_call('%s %s' % (shell, tmpfile), shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '/bin/bash /tmp/tmptP0K6H/run' returned non-zero exit status 137

```

**Comment by mgogoulos** [comment]
Hi, 

most probably you are running this on a low resources server and grunt process doesn't manage to complete but it get's killed by the system. What are the server specs? It needs at least 1G to run properly, while 2G would be more realistic. 

Regards,
Markos

**Comment by yawboateng** [comment]
yea, upgrading to 2GB worked. Thanks
