### ISSUE TITLE
Docker image fails to start due to missing pytest

### ISSUE THREAD

**Issue by aaronkurtz** [mistio/mist.io#724]
The current docker image (68f49180233b) fails to start for me.

Looking at the logs, I found this in the uwsgi stderr log.

```
Loading paste environment: config:/home/mist/mist.io/uwsgi.ini
Traceback (most recent call last):
  File "/home/mist/mist.io/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 24
7, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/home/mist/mist.io/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 27
2, in loadobj
    return context.create()
  File "/home/mist/mist.io/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 71
0, in create
    return self.object_type.invoke(self)
  File "/home/mist/mist.io/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/loadwsgi.py", line 14
6, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/home/mist/mist.io/eggs/PasteDeploy-1.5.2-py2.7.egg/paste/deploy/util.py", line 55, in
 fix_call
    val = callable(*args, **kw)
  File "/home/mist/mist.io/src/mist/io/__init__.py", line 83, in main
    configurator.scan()
  File "/home/mist/mist.io/eggs/pyramid-1.4-py2.7.egg/pyramid/config/__init__.py", line 947, i
n scan
    ignore=ignore)
  File "/home/mist/mist.io/eggs/venusian-1.0-py2.7.egg/venusian/__init__.py", line 205, in sca
n
    __import__(modname)
  File "/home/mist/mist.io/src/mist/io/tests/api/conftest.py", line 1, in <module>
    import pytest
ImportError: No module named pytest
```

As a workaround, I got this running by deleting /home/mist/mist.io/src/mist/io/tests/ and restarting uwsgi.

**Comment by mgogoulos** [comment]
Hi, 

thanks a lot for reporting this. We need to update the docker image, will do that in the following days. 

Regards,
Markos

**Comment by mgogoulos** [comment]
Hi @aaronkurtz ,
mist.io image has been updated, so please do a docker update and start a new container. 

Regards,
Markos

**Comment by cpsaltis** [comment]
Just out of curiosity, what problem are you looking to solve with Mist.io @aaronkurtz?
