### ISSUE TITLE
Buildout fail on funtoo: TypeError('Option values must be strings', value)

### ISSUE THREAD

**Issue by chronossc** [mistio/mist.io#740]
So, I'm trying to install in Funtoo but get this error (looks like bug):

```
(mistio) mistio@kenobi ~/app/mistio/mist.io $ buildout -v            
Installing 'mr.developer'.
We have no distributions for mr.developer that satisfies 'mr.developer'.
Getting distribution for 'mr.developer'.
Running easy_install:
"/usr/bin/python2.7" "-c" "from setuptools.command.easy_install import main; main()" "-mZUNxd" "/home/mistio/app/mistio/mist.io/eggs/tmpjWWzaI" "-q" "/tmp/tmpae5eLeget_dist/mr.developer-1.34.zip"
path=/usr/lib64/python2.7/site-packages

Got mr.developer 1.34.
Picked: mr.developer = 1.34
mr.developer: Queued 'deploy_collectd' for checkout.
mr.developer: Queued 'libcloud' for checkout.
mr.developer: Cloned 'deploy_collectd' with git.
mr.developer: Cloned 'libcloud' with git.
Installing 'zc.buildout', 'setuptools'.
We have a develop egg: zc.buildout 2.5.1
We have a develop egg: setuptools 20.10.1
Adding find link 'https://pypi.python.org/packages/source/c/certifi/certifi-2016.2.28.tar.gz#md5=5d672aa766e1f773c75cfeccd02d3650' from setuptools 20.10.1
Adding find link 'https://pypi.python.org/packages/source/w/wincertstore/wincertstore-0.2.zip#md5=ae728f2f007185648d0c7a8679b361e2' from setuptools 20.10.1
Running '/usr/lib64/python-exec/python2.7/buildout'.
Local buildout is '/home/mistio/app/mistio/mist.io/bin/buildout'.
Not upgrading because not running a local buildout command.
Develop: '/home/mistio/app/mistio/mist.io/.'
warning: no files found matching '*.ico' under directory 'mistio'
warning: no files found matching '*.png' under directory 'mistio'
warning: no files found matching '*.css' under directory 'mistio'
warning: no files found matching '*.gif' under directory 'mistio'
warning: no files found matching '*.jpg' under directory 'mistio'
warning: no files found matching '*.pt' under directory 'mistio'
warning: no files found matching '*.txt' under directory 'mistio'
warning: no files found matching '*.mak' under directory 'mistio'
warning: no files found matching '*.mako' under directory 'mistio'
warning: no files found matching '*.js' under directory 'mistio'
warning: no files found matching '*.html' under directory 'mistio'
warning: no files found matching '*.xml' under directory 'mistio'
Develop: '/home/mistio/app/mistio/mist.io/src/libcloud'
no previously-included directories found matching 'libcloud/test/secrets.py'
Installing 'zc.recipe.egg'.
We have no distributions for zc.recipe.egg that satisfies 'zc.recipe.egg>=2.0.0a3'.
Getting distribution for 'zc.recipe.egg>=2.0.0a3'.
Running easy_install:
"/usr/bin/python2.7" "-c" "from setuptools.command.easy_install import main; main()" "-mZUNxd" "/home/mistio/app/mistio/mist.io/eggs/tmpLK0ayu" "-q" "/tmp/tmpsN63Pgget_dist/zc.recipe.egg-2.0.3.tar.gz"
path=/usr/lib64/python2.7/site-packages

Got zc.recipe.egg 2.0.3.
Picked: zc.recipe.egg = 2.0.3
Installing 'collective.recipe.pip'.
We have no distributions for collective.recipe.pip that satisfies 'collective.recipe.pip'.
Getting distribution for 'collective.recipe.pip'.
Running easy_install:
"/usr/bin/python2.7" "-c" "from setuptools.command.easy_install import main; main()" "-mZUNxd" "/home/mistio/app/mistio/mist.io/eggs/tmpABnyKr" "-q" "/tmp/tmpNSTKHVget_dist/collective.recipe.pip-0.3.2.tar.gz"
path=/usr/lib64/python2.7/site-packages

warning: no files found matching '*.rst' under directory 'collective'
Got collective.recipe.pip 0.3.2.
Adding find link 'https://github.com/minddistrict/mr.scripty/archive/4bbfa2b48b7bc8a215c80a19e61ac39d0c9545aa.zip#egg=mr.scripty' from collective.recipe.pip 0.3.2
Picked: collective.recipe.pip = 0.3.2
pip.utils: lzma module is not available
pip.vcs: Registered VCS backend: git
pip.vcs: Registered VCS backend: hg
pip.vcs: Registered VCS backend: svn
pip.vcs: Registered VCS backend: bzr
While:
  Installing.
  Getting section pip.
  Initializing section pip.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/zc/buildout/buildout.py", line 1946, in main
    getattr(buildout, command)(args)
  File "/usr/lib64/python2.7/site-packages/zc/buildout/buildout.py", line 510, in install
    [self[part]['recipe'] for part in install_parts]
  File "/usr/lib64/python2.7/site-packages/zc/buildout/buildout.py", line 1098, in __getitem__
    options._initialize()
  File "/usr/lib64/python2.7/site-packages/zc/buildout/buildout.py", line 1202, in _initialize
    self.initialize()
  File "/usr/lib64/python2.7/site-packages/zc/buildout/buildout.py", line 1211, in initialize
    self.recipe = recipe_class(buildout, name, self)
  File "/home/mistio/app/mistio/mist.io/eggs/collective.recipe.pip-0.3.2-py2.7.egg/collective/recipe/pip/__init__.py", line 41, in __init__
    self.process()
  File "/home/mistio/app/mistio/mist.io/eggs/collective.recipe.pip-0.3.2-py2.7.egg/collective/recipe/pip/__init__.py", line 68, in process
    self.options['eggs'] = "\n".join(sorted(set(eggs)))
  File "/usr/lib64/python2.7/site-packages/zc/buildout/buildout.py", line 1333, in __setitem__
    raise TypeError('Option values must be strings', value)
TypeError: ('Option values must be strings', u'PasteDeploy==1.5.2\nPasteScript==2.0.2\nPyYAML==3.11\nSphinx==1.3.5\namqp==1.4.6\nansible==1.9.3\napache-libcloud\nbehave==1.2.5\nbehaving==1.4.1\ncelery==3.1.17\ngevent-subprocess==0.1.1\ngevent==1.0.2\nnetaddr==0.7.18\nparamiko==1.16.0\npika==0.10.0\npycrypto==2.6.1\npyramid==1.4\npytest==2.8.7\npython-memcached==1.57\nrequests==2.7.0\nselenium==2.52.0\nsockjs-tornado==1.0.2\nsphinx-bootstrap-theme==0.4.7\nsphinx-rtd-theme==0.1.8\nsphinxcontrib-httpdomain==1.4.0\nwebsocket-client==0.29.0')
```

**Comment by mgogoulos** [comment]
Hi, what version of python does your OS have?

**Comment by chronossc** [comment]
At Funtoo we have 2.7 and 3.4, I'm using 2.7 for this virtualenv and also system default:

```
mistio@kenobi ~ $ eselect python list
Available Python interpreters:
  [1]   python2.7 *
  [2]   python3.4
mistio@kenobi ~ $ workon mistio
(mistio) mistio@kenobi ~/app/mistio $ python -V
Python 2.7.11
(mistio) mistio@kenobi ~/app/mistio $ which python
/home/mistio/.virtualenvs/mistio/bin/python
```

**Comment by mgogoulos** [comment]
please follow the instructions and make sure you create a virtualenv which uses python2.7 with no-site-packages. 

The buildout can't run on python3 so the issue above indicates somehow a python3 lib is being used

```
git clone https://github.com/mistio/mist.io.git
cd mist.io
virtualenv --no-site-packages . -p /path_to_python2.7
./bin/python bootstrap.py
./bin/buildout -v
```

**Comment by chronossc** [comment]
Same issue:

```
mistio@kenobi ~/app/mistio $ cd mist.io/
mistio@kenobi ~/app/mistio/mist.io $ virtualenv --no-site-packages . -p python2.7
Already using interpreter /usr/bin/python2.7
New python executable in /home/mistio/app/mistio/mist.io/bin/python2.7
Also creating executable in /home/mistio/app/mistio/mist.io/bin/python
Installing setuptools, pip, wheel...done.
mistio@kenobi ~/app/mistio/mist.io $ ./bin/python bootstrap.py
Creating directory '/home/mistio/app/mistio/mist.io/develop-eggs'.
Generated script '/home/mistio/app/mistio/mist.io/bin/buildout'.
mistio@kenobi ~/app/mistio/mist.io $ ./bin/buildout -v
Installing 'mr.developer'.
We have the best distribution that satisfies 'mr.developer'.
Picked: mr.developer = 1.34
mr.developer: Queued 'deploy_collectd' for checkout.
mr.developer: Queued 'libcloud' for checkout.
mr.developer: Skipped checkout of existing package 'libcloud'.
mr.developer: Skipped checkout of existing package 'deploy_collectd'.
Installing 'zc.buildout', 'setuptools'.
We have the best distribution that satisfies 'zc.buildout>=2.5.1'.
Picked: zc.buildout = 2.5.1
We have a develop egg: setuptools 20.10.1
Adding find link 'https://pypi.python.org/packages/source/c/certifi/certifi-2016.2.28.tar.gz#md5=5d672aa766e1f773c75cfeccd02d3650' from setuptools 20.10.1
Adding find link 'https://pypi.python.org/packages/source/w/wincertstore/wincertstore-0.2.zip#md5=ae728f2f007185648d0c7a8679b361e2' from setuptools 20.10.1
Develop: '/home/mistio/app/mistio/mist.io/.'
warning: no files found matching '*.ico' under directory 'mistio'
warning: no files found matching '*.png' under directory 'mistio'
warning: no files found matching '*.css' under directory 'mistio'
warning: no files found matching '*.gif' under directory 'mistio'
warning: no files found matching '*.jpg' under directory 'mistio'
warning: no files found matching '*.pt' under directory 'mistio'
warning: no files found matching '*.txt' under directory 'mistio'
warning: no files found matching '*.mak' under directory 'mistio'
warning: no files found matching '*.mako' under directory 'mistio'
warning: no files found matching '*.js' under directory 'mistio'
warning: no files found matching '*.html' under directory 'mistio'
warning: no files found matching '*.xml' under directory 'mistio'
Develop: '/home/mistio/app/mistio/mist.io/src/libcloud'
no previously-included directories found matching 'libcloud/test/secrets.py'
Installing 'zc.recipe.egg'.
We have the best distribution that satisfies 'zc.recipe.egg>=2.0.0a3'.
Picked: zc.recipe.egg = 2.0.3
Installing 'collective.recipe.pip'.
We have the best distribution that satisfies 'collective.recipe.pip'.
Adding find link 'https://github.com/minddistrict/mr.scripty/archive/4bbfa2b48b7bc8a215c80a19e61ac39d0c9545aa.zip#egg=mr.scripty' from collective.recipe.pip 0.3.2
Picked: collective.recipe.pip = 0.3.2
pip.utils: lzma module is not available
pip.vcs: Registered VCS backend: git
pip.vcs: Registered VCS backend: hg
pip.vcs: Registered VCS backend: svn
pip.vcs: Registered VCS backend: bzr
While:
  Installing.
  Getting section pip.
  Initializing section pip.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/mistio/app/mistio/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/home/mistio/app/mistio/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 550, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/mistio/app/mistio/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1135, in __getitem__
    options._initialize()
  File "/home/mistio/app/mistio/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1239, in _initialize
    self.initialize()
  File "/home/mistio/app/mistio/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1248, in initialize
    self.recipe = recipe_class(buildout, name, self)
  File "/home/mistio/app/mistio/mist.io/eggs/collective.recipe.pip-0.3.2-py2.7.egg/collective/recipe/pip/__init__.py", line 41, in __init__
    self.process()
  File "/home/mistio/app/mistio/mist.io/eggs/collective.recipe.pip-0.3.2-py2.7.egg/collective/recipe/pip/__init__.py", line 68, in process
    self.options['eggs'] = "\n".join(sorted(set(eggs)))
  File "/home/mistio/app/mistio/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/buildout.py", line 1370, in __setitem__
    raise TypeError('Option values must be strings', value)
TypeError: ('Option values must be strings', u'PasteDeploy==1.5.2\nPasteScript==2.0.2\nPyYAML==3.11\nSphinx==1.3.5\namqp==1.4.6\nansible==1.9.3\napache-libcloud\nbehave==1.2.5\nbehaving==1.4.1\ncelery==3.1.17\ngevent-subprocess==0.1.1\ngevent==1.0.2\nnetaddr==0.7.18\nparamiko==1.16.0\npika==0.10.0\npycrypto==2.6.1\npyramid==1.4\npytest==2.8.7\npython-memcached==1.57\nrequests==2.7.0\nselenium==2.52.0\nsockjs-tornado==1.0.2\nsphinx-bootstrap-theme==0.4.7\nsphinx-rtd-theme==0.1.8\nsphinxcontrib-httpdomain==1.4.0\nwebsocket-client==0.29.0')
mistio@kenobi ~/app/mistio/mist.io $ 
```

**Comment by marcaurele** [comment]
I got the same problem, running as well python 2.7.11 on OSX

**Comment by mgogoulos** [comment]
These all seem to be related with https://github.com/pypa/setuptools/issues/476 / https://github.com/buildout/buildout/issues/283

**Comment by X4** [comment]
Error #283 still persists. But I found a fix, which I'll report right after my error log. Fyi: I tried using setuptools 19, 19.1.1 etc. using various ways, but that didn't fix the problem. Anyway here's my log:

````bash
❯ ./bin/buildout -v
Installing 'mr.developer'.
We have the best distribution that satisfies 'mr.developer'.
Picked: mr.developer = 1.34
mr.developer: Queued 'deploy_collectd' for checkout.
mr.developer: Queued 'libcloud' for checkout.
mr.developer: Skipped checkout of existing package 'deploy_collectd'.
mr.developer: Skipped checkout of existing package 'libcloud'.
Installing 'zc.buildout', 'setuptools'.
We have the best distribution that satisfies 'zc.buildout>=2.5.1'.
Picked: zc.buildout = 2.5.1
We have the best distribution that satisfies 'setuptools'.
Adding find link 'https://pypi.python.org/packages/source/c/certifi/certifi-2016.2.28.tar.gz#md5=5d672aa76
6e1f773c75cfeccd02d3650' from setuptools 21.0.0
Adding find link 'https://pypi.python.org/packages/source/w/wincertstore/wincertstore-0.2.zip#md5=ae728f2f
007185648d0c7a8679b361e2' from setuptools 21.0.0
Picked: setuptools = 21.0.0
Develop: '/home/john-henry/Workspace/external/dashboards/mist.io/.'
warning: no files found matching '*.ico' under directory 'mistio'
warning: no files found matching '*.png' under directory 'mistio'
warning: no files found matching '*.css' under directory 'mistio'
warning: no files found matching '*.gif' under directory 'mistio'
warning: no files found matching '*.jpg' under directory 'mistio'
warning: no files found matching '*.pt' under directory 'mistio'
warning: no files found matching '*.txt' under directory 'mistio'
warning: no files found matching '*.mak' under directory 'mistio'
warning: no files found matching '*.mako' under directory 'mistio'
warning: no files found matching '*.js' under directory 'mistio'
warning: no files found matching '*.html' under directory 'mistio'
warning: no files found matching '*.xml' under directory 'mistio'
Develop: '/home/john-henry/Workspace/external/dashboards/mist.io/src/libcloud'
no previously-included directories found matching 'libcloud/test/secrets.py'
Installing 'zc.recipe.egg'.
We have the best distribution that satisfies 'zc.recipe.egg>=2.0.0a3'.
Picked: zc.recipe.egg = 2.0.3
Installing 'collective.recipe.pip'.
We have the best distribution that satisfies 'collective.recipe.pip'.
Adding find link 'https://github.com/minddistrict/mr.scripty/archive/4bbfa2b48b7bc8a215c80a19e61ac39d0c954
5aa.zip#egg=mr.scripty' from collective.recipe.pip 0.3.2
Picked: collective.recipe.pip = 0.3.2
pip.utils: lzma module is not available
pip.vcs: Registered VCS backend: git
pip.vcs: Registered VCS backend: hg
pip.vcs: Registered VCS backend: svn
pip.vcs: Registered VCS backend: bzr
While:
  Installing.
  Getting section pip.
  Initializing section pip.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/john-henry/Workspace/external/dashboards/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/bu
ildout.py", line 1992, in main
    getattr(buildout, command)(args)
  File "/home/john-henry/Workspace/external/dashboards/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/bu
ildout.py", line 550, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/john-henry/Workspace/external/dashboards/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/bu
ildout.py", line 1135, in __getitem__
    options._initialize()
  File "/home/john-henry/Workspace/external/dashboards/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/bu
ildout.py", line 1239, in _initialize
    self.initialize()
  File "/home/john-henry/Workspace/external/dashboards/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/bu
ildout.py", line 1248, in initialize
    self.recipe = recipe_class(buildout, name, self)
  File "/home/john-henry/Workspace/external/dashboards/mist.io/eggs/collective.recipe.pip-0.3.2-py2.7.egg/coll
ective/recipe/pip/__init__.py", line 41, in __init__
    self.process()
  File "/home/john-henry/Workspace/external/dashboards/mist.io/eggs/collective.recipe.pip-0.3.2-py2.7.egg/coll
ective/recipe/pip/__init__.py", line 68, in process
    self.options['eggs'] = "\n".join(sorted(set(eggs)))
  File "/home/john-henry/Workspace/external/dashboards/mist.io/eggs/zc.buildout-2.5.1-py2.7.egg/zc/buildout/bu
ildout.py", line 1370, in __setitem__
    raise TypeError('Option values must be strings', value)
TypeError: ('Option values must be strings', u'PasteDeploy==1.5.2\nPasteScript==2.0.2\nPyYAML==3.11\nSphin
x==1.3.5\namqp==1.4.6\nansible==1.9.3\napache-libcloud\nbehave==1.2.5\nbehaving==1.4.1\ncelery==3.1.17\nge
vent-subprocess==0.1.1\ngevent==1.0.2\nnetaddr==0.7.18\nparamiko==1.16.0\npika==0.10.0\npycrypto==2.6.1\np
yramid==1.4\npytest==2.8.7\npython-memcached==1.57\nrequests==2.7.0\nselenium==2.52.0\nsockjs-tornado==1.0
.2\nsphinx-bootstrap-theme==0.4.7\nsphinx-rtd-theme==0.1.8\nsphinxcontrib-httpdomain==1.4.0\nwebsocket-cli
ent==0.29.0')
````
The error's original cause has been discussed already in #283, however it either reappeared or wasn't ever fixed. The snippet below, which I assume should resemble a 'lazy evaluation' to batch install the python eggs, just fails badly. **I can create a PR with the fix below if you want.** 

````ìni
[pip]
recipe = collective.recipe.pip
configs = requirements.txt

````
You can easily fix the whole buildout drama, by replacing line 38-58 in `buildout.cfg` with the config below:

````ini
[mist]
recipe = zc.recipe.egg
dependent-scripts = true
eggs =
    mist.io
    PasteScript
    ${buildout:eggs}

[uwsgi]
recipe = unweb.recipe.uwsgi
url = http://projects.unbit.it/downloads/uwsgi-2.0.11.2.tar.gz
eggs =
    ${mist:eggs}

[pip]
recipe = collective.recipe.cmd
shell = /bin/bash
on_install = true
on_update = true
cmds = ./bin/pip install -r requirements.txt; echo $'\npip modules installed.\n'

````

**Comment by ridha** [comment]
This issue is due to a change in the recent version of pip >8 ( See https://github.com/pypa/pip/pull/3547/files). collective.recipe.pip (0.3.4) is updated to support recent version of pip; let me know if that doesn't address the issue.

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io
