### ISSUE TITLE
Adding multiple KVM based hosts causes browser lockups.

### ISSUE THREAD

**Issue by fuqqer** [mistio/mist.io#883]
Mist.io works great for one KVM/libvirt based hypervisor. Adding a second or third causes the page that's being served to lock up the browser accessing mist.io.

The mist.io server is idle and the logs show connections to the hypervisors to list VMs, but the mist.io interface and any browser (chrome, chromium, firefox, seamonkey) all use 100% cpu on a machine accessing the mist.io page.

**Comment by fuqqer** [comment]
My browser has more than 550 warnings related to the ember-template-compiler. I'm not sure if they're related. 
﻿
ember-template-compiler.js:286 DEPRECATION: Global lookup of Mist from a Handlebars template is deprecated.
        at getGlobal (http://172.16.1.188:8000/resources/dist/ember/ember.debug.js:8392:32)
        at Object.getRoot (http://172.16.1.188:8000/resources/dist/ember/ember.debug.js:8367:15)
        at Object.get (http://172.16.1.188:8000/resources/dist/ember/ember-template-compiler.js:15405:27)
        at Object.get (http://172.16.1.188:8000/resources/dist/ember/ember-template-compiler.js:14143:24)
        at Object.acceptExpression (http://172.16.1.188:8000/resources/dist/ember/ember-template-compiler.js:14111:28)
        at Object.acceptParams (http://172.16.1.188:8000/resources/dist/ember/ember-template-compiler.js:14125:23)
        at Object.linkParamsAndHash (http://172.16.1.188:8000/resources/dist/ember/ember-template-compiler.js:14164:33)
        at Object.block (http://172.16.1.188:8000/resources/dist/ember/ember-template-compiler.js:14181:32)
        at RenderResult.populateNodes (http://172.16.1.188:8000/resources/dist/ember/ember-template-compiler.js:15849:19)

**Comment by mgogoulos** [comment]
The problem with the UI being unstable is something we have met in cases where many VMs (usually more than 100) are listed, rather than having added many clouds/backends. The new UI that is going to be released soon will be able to handle big numbers of VMs and other resources without the problems of the current one.

**Comment by fuqqer** [comment]
This happens with 3 libvirt based hypervisors and less than 40 VMs.

**Comment by fribergr** [comment]
This occurs for me too. I'm running the docker image, connecting to KVM on the same host that is running docker.
One KVM-host with 21 VMs causing chrome to be unresponsive and CPU-usage is pegged at 100%.

Any idea when this will be solved?

For reference: I'm running Ubuntu 16.10 with latest Chrome (also tried Firefox) on client, connecting through a Apache proxy with basic auth enabled over SSL which proxies to my docker-host (Debian stable) on port 8000.

**Comment by mgogoulos** [comment]
Hi, 
performance related issues are fixed on the new UI that will be part of the next release. This has delayed but we are now very close to performing this release, most probably in the next couple of weeks. 

Best,
Markos

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io

This includes a stable and functional new UI
