### ISSUE TITLE
Starting celery failed (upstream bug in celery/kombu)

### ISSUE THREAD

**Issue by dmeijboom** [mistio/mist.io#890]
After building mist.io and starting all services celery (and another service, can't remember which one) errored immidiately. Looking at the logs I saw this:

```Traceback (most recent call last):
  File "/home/mist/mist.io/bin/celery", line 67, in <module>
    import celery.__main__
  File "/home/mist/mist.io/eggs/celery-3.1.17-py2.7.egg/celery/__init__.py", line 130, in <module>
    from celery import five
  File "/home/mist/mist.io/eggs/celery-3.1.17-py2.7.egg/celery/five.py", line 149, in <module>
    from kombu.utils.compat import OrderedDict  # noqa
  File "/home/mist/mist.io/eggs/kombu-3.0.26-py2.7.egg/kombu/utils/__init__.py", line 19, in <module>
    from uuid import UUID, uuid4 as _uuid4, _uuid_generate_random
ImportError: cannot import name _uuid_generate_random```

It looks like a bug in celery/kombu (see: https://github.com/celery/kombu/issues/551) which is fixed in 3.0.30.

I finally fixed it by removing some version contraints in buildout.cfg and randomly upping versions in requirements.txt however I'm aware that this _may_ or _may not_ work. These are the files currently:

**requirements.txt**
```ansible==1.9.3
apache-libcloud
amqp==1.4.9
behave==1.2.5
behaving==1.4.1
celery==3.1.19
gevent==1.0.2
gevent-subprocess==0.1.1
netaddr==0.7.18
paramiko==1.16.0
PasteDeploy==1.5.2
PasteScript==2.0.2
pika==0.10.0
pycrypto==2.6.1
pyramid==1.4
pytest==2.8.7
python-memcached==1.57
PyYAML==3.11
requests==2.7.0
selenium==2.52.0
sockjs-tornado==1.0.2
Sphinx==1.3.5
sphinx-bootstrap-theme==0.4.7
sphinx-rtd-theme==0.1.8
sphinxcontrib-httpdomain==1.4.0
websocket-client==0.29.0
splinter==0.7.3```

**buildout.cfg**
```[buildout]
extensions =
    mr.developer

parts =
    pip
    cloudpy
    mist
    uwsgi
    haproxy
    rabbitmq
    rabbitmq-env
    rabbitmq-conf
    libevent
    memcached
    supervisor
    nodejs
    node_modules
    bower
    grunt
    devtools
    pylint
    behave
    chromedriver
    chromedriver-mac

develop = .
          src/libcloud

sources = sources
versions = versions
auto-checkout = *

eggs =

allow-hosts=*.python.org

[mist]
recipe = zc.recipe.egg
dependent-scripts = true
eggs =
    mist.io
    PasteScript
    ${pip:eggs}
    ${buildout:eggs}

[uwsgi]
recipe = unweb.recipe.uwsgi
url = http://projects.unbit.it/downloads/uwsgi-2.0.11.2.tar.gz
eggs =
    ${mist:eggs}

[pip]
recipe = collective.recipe.pip
configs = requirements.txt

[haproxy]
recipe = plone.recipe.haproxy
target = generic
url = http://haproxy.1wt.eu/download/1.5/src/haproxy-1.5.14.tar.gz

[nodejs]
recipe = gp.recipe.node
version = 0.12.7
npms = grunt-cli bower browserify requirejs
scripts = grunt bower browserify r.js

[bower]
recipe = collective.recipe.cmd
shell = /bin/bash
on_install = true
on_update = true
cmds = ./bin/bower install --config.interactive=false; echo $'\nBower modules installed.\n'

[node_modules]
recipe = collective.recipe.cmd
shell = /bin/bash
on_install = true
on_update = true
cmds = NODE_PATH="" bin/npm install .; echo $'\nNodeJS modules installed.\n'

[grunt]
recipe = collective.recipe.cmd
shell = /bin/bash
on_install = true
on_update = true
cmds = ./bin/grunt --force && ln -fs `pwd`/dist `pwd`/src/mist/io/static/dist

[rabbitmq]
recipe = gocept.download
url = http://www.rabbitmq.com/releases/rabbitmq-server/v3.3.0/rabbitmq-server-generic-unix-3.3.0.tar.gz
md5sum = 12a54f6ed64e5118cee7a6d1f7b8111d

[rabbitmq-env]
recipe = collective.recipe.template
input = ${buildout:directory}/templates/rabbitmq-env.conf.in
output = ${buildout:parts-directory}/rabbitmq/etc/rabbitmq/rabbitmq-env.conf

[rabbitmq-conf]
recipe = collective.recipe.template
input = ${buildout:directory}/templates/rabbitmq.config.in
output = ${buildout:parts-directory}/rabbitmq/etc/rabbitmq/rabbitmq.config

[libevent]
recipe = hexagonit.recipe.cmmi
url = https://github.com/libevent/libevent/releases/download/release-2.0.22-stable/libevent-2.0.22-stable.tar.gz
environment =
	CFLAGS=-I/usr/local/opt/openssl/include

[memcached]
recipe = hexagonit.recipe.cmmi
url = http://www.memcached.org/files/memcached-1.4.23.tar.gz
configure-options = --with-libevent=${libevent:location} --bindir=${buildout:directory}/bin

[supervisor]
recipe = collective.recipe.supervisor
port = localhost:9003
programs =
    10 haproxy ${buildout:bin-directory}/haproxy [ -f haproxy.conf -db ] ${buildout:directory}
    20 sockjs ${buildout:directory}/bin/cloudpy [ serve.py 8081 ] ${buildout:directory}
    40 uwsgi ${buildout:directory}/bin/uwsgi [ -x ${buildout:parts-directory}/uwsgi/uwsgi.xml --paste-logger --ini-paste uwsgi.ini ] ${buildout:directory}
    60 rabbitmq ${buildout:parts-directory}/rabbitmq/sbin/rabbitmq-server ${buildout:directory}
    70 celery ${buildout:bin-directory}/celery [ worker -A mist.io.tasks -n celery@localhost -l WARNING -Ofair ] ${buildout:directory}
    80 memcache ${buildout:bin-directory}/memcached [ -l 127.0.0.1 ]
    90 hub-shell ${buildout:directory}/bin/cloudpy [ src/mist/io/hub/shell.py server ] ${buildout:directory}

[cloudpy]
recipe = zc.recipe.egg
eggs =
    ipython
    Pillow
    ${mist:eggs}
scripts = ipython=cloudpy

[devtools]
recipe = zc.recipe.egg:scripts
eggs =
    pep8
    ${mist:eggs}

[pylint]
recipe = zc.recipe.egg
eggs =
    pylint
    ${mist:eggs}
scripts = pylint
entry-points = pylint=pylint.lint:Run
arguments = sys.argv[1:]

[behave]
recipe = zc.recipe.egg
eggs = ${mist:eggs}
interpreter = ${buildout:directory}/cloudpy

[chromedriver]
recipe = hexagonit.recipe.download
url = http://chromedriver.storage.googleapis.com/2.20/chromedriver_linux64.zip

[chromedriver-mac]
recipe = hexagonit.recipe.download
url = http://chromedriver.storage.googleapis.com/2.20/chromedriver_mac32.zip

[sources]
libcloud = git https://github.com/mistio/libcloud.git branch=mistio
deploy_collectd = git https://github.com/mistio/deploy_collectd.git egg=false

[versions]
pyramid = 1.4
gevent = 1.0.2
Pillow = 2.9.0```

I'm running Ubuntu 16.04.1 LTS and I have kvm installed.

**Comment by mbround18** [comment]
This is an issue for me as well, is it currently being looked into?

**Comment by mgogoulos** [comment]
Hi @mbround18 , the new open source release will be out until the end of the month, and this will also be released as a docker image. Please be patient until then

Regards

**Comment by mbround18** [comment]
@mgogoulos Ill take that as a yes it is being looked into, thank you for the information and im eagerly awaiting the new release :)

**Comment by joshfrogers** [comment]
@mgogoulos I'm still having this issue - is the latest open source release available? If not, what would the timeline for this be?

**Comment by mgogoulos** [comment]
Hi, 

this has taken some while because we decided to move more features from the Saas version to the open source. It will eventually be out in the next 2-3 weeks, stay tuned!

**Comment by mgogoulos** [comment]
Version 2 is out, comes with an easier installation process using Docker Compose and many new features, check updated instructions on https://github.com/mistio/mist.io
