### ISSUE TITLE
Unable to use G Suite SMTP settings

### ISSUE THREAD

**Issue by boristunity** [mistio/mist.io#908]
When trying to configure custom SMTP server, and trying to use the `forgot password`, the session hangs out.
This is the output of the api
~~~
api_1                   | [pid: 49|app: 0|req: 5/5] 172.18.0.15 () {46 vars in 963 bytes} [Mon Jun 26 13:47:31 2017] POST /forgot => generated 21 bytes in 131226 msecs (HTTP/1.0 500) 2 headers in 98 bytes (1 switches on core 0)
api_1                   | 2017-06-26 13:50:29,561 ERROR [mist.api.logs.methods][uWSGIWorker1Core0] User None does not exist
api_1                   | [pid: 49|app: 0|req: 6/6] 172.18.0.15 () {46 vars in 963 bytes} [Mon Jun 26 13:50:29 2017] POST /forgot => generated 2 bytes in 26 msecs (HTTP/1.0 200) 2 headers in 78 bytes (1 switches on core 0)
api_1                   | [pid: 49|app: 0|req: 7/7] 172.18.0.15 () {46 vars in 953 bytes} [Mon Jun 26 13:51:20 2017] POST /login => generated 113 bytes in 126 msecs (HTTP/1.0 200) 3 headers in 170 bytes (1 switches on core 0)
api_1                   | path
api_1                   | [pid: 49|app: 0|req: 8/8] 172.18.0.15 () {40 vars in 870 bytes} [Mon Jun 26 13:51:20 2017] GET / => generated 1768 bytes in 82 msecs (HTTP/1.0 200) 2 headers in 81 bytes (1 switches on core 0)
api_1                   | [pid: 49|app: 0|req: 9/9] 172.18.0.15 () {38 vars in 898 bytes} [Mon Jun 26 13:51:25 2017] GET /api/v1/logs?limit=50&filter=owner_id%3A7fc933b59c3a40c69044b55c7abbf3e2 => generated 45046 bytes in 42 msecs (HTTP/1.0 200) 2 headers in 74 bytes (1 switches on core 0)
~~~

The content of the `./config/settings.py` is:

~~~
"""User defined settings"""

## Configure external url.
#CORE_URI = "http:/104.155.137.222"

## Verify SSL outgoing SSL connections.
#SSL_VERIFY = False

## Configure email settings.
# MAILER_SETTINGS = {
#     'mail.host': "smtp-relay.gmail.com",
#     'mail.port': "587",
#     'mail.tls': False,
#     'mail.starttls': False,
#     'mail.username': "",
#     'mail.password': "",
# }

MAILER_SETTINGS = { 'mail.host': "smtp-relay.gmail.com",'mail.port': "578", 'mail.tls': False,'mail.starttls': False }

## Configure whether to serve bundled/minified UI assets.
# JS_BUILD = True

## Allow mist.io to connect to localhost.
#ALLOW_CONNECT_LOCALHOST = False

## Allow mist.io to connect to private IP addresses.
# ALLOW_CONNECT_PRIVATE = False

## API token for github.
# GITHUB_BOT_TOKEN = ""
~~~

The SMTP relay of google is working, tested it on localhost with telnet session and commands.
It does not requires any credentials and does not requires the use of TLS/SSL

---

## Update:
Not sure if its related, but when I try to configure `ORGANIZATION ALERT EMAIL` under the `Organisation Profile` settings, I get the error:
![screen shot 2017-06-26 at 17 15 23](https://user-images.githubusercontent.com/20415463/27543575-3d5691c2-5a93-11e7-860e-019ed02f724f.png)
And the logs at api are:

~~~
api_1                   | 2017-06-26 14:17:23,346 CRITI [mist.api.views][uWSGIWorker2Core0] Uncaught non-mist exception? WTF!
api_1                   | Traceback (most recent call last):
api_1                   |   File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
api_1                   |     response = handler(request)
api_1                   |   File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 161, in handle_request
api_1                   |     response = view_callable(context, request)
api_1                   |   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 586, in __call__
api_1                   |     return view(context, request)
api_1                   |   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 319, in attr_view
api_1                   |     return view(context, request)
api_1                   |   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 295, in predicate_wrapper
api_1                   |     return view(context, request)
api_1                   |   File "/mist.api/src/mist/api/helpers.py", line 844, in logging_view
api_1                   |     response = func(context, request)
api_1                   |   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 345, in rendered_view
api_1                   |     result = view(context, request)
api_1                   |   File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 491, in _requestonly_view
api_1                   |     response = view(request)
api_1                   |   File "/mist.api/src/mist/api/views.py", line 2015, in edit_organization
api_1                   |     from mist.core.methods import update_monitoring_options
api_1                   | ImportError: No module named core.methods
api_1                   |
api_1                   | 2017-06-26 14:17:23,402 INFO  [mist.api.helpers][uWSGIWorker2Core0] Bad exception occured, logging to rabbitmq
api_1                   | 2017-06-26 14:17:23,432 INFO  [mist.api.helpers][uWSGIWorker2Core0] Bad exception occured, logging to file
api_1                   | [pid: 96|app: 0|req: 3/9] 172.18.0.15 () {46 vars in 1036 bytes} [Mon Jun 26 14:17:23 2017] PUT /api/v1/org/7fc933b59c3a40c69044b55c7abbf3e2 => generated 21 bytes in 124 msecs (HTTP/1.0 500) 2 headers in 98 bytes (1 switches on core 0)
~~~

**Comment by dimrozakis** [comment]
hey @boristunity 

Any chance you need to set `mail.tls` to True for this to work?

**Comment by boristunity** [comment]
@dimrozakis 
I don't want to use the TLS authentication, because this SMTP relay service is being used by another services in my environment

**Comment by dimrozakis** [comment]
@boristunity how exactly are you authenticating to the gmail smtp relay server?

**Comment by dimrozakis** [comment]
I just saw that you edited the issue's description. The traceback you got seems like a legitimate and separate issue.

**Comment by boristunity** [comment]
@dimrozakis I have no authentication process to google's SMTP relay server,
The only guard I have is the source IP, only the permitted WAN IP's can access it and use it without any authentication.
Here is google's [reference](https://support.google.com/a/answer/176600?hl=en) about this service.

---

So should I open new issue about the `ORGANIZATION ALERT EMAIL under the Organisation ?Profile`

**Comment by mgogoulos** [comment]
Hi, 
I'm closing this as I've opened an issue on our private tracker regarding the ORGANIZATION alert email - the real issue here is that it shouldn't be available, as the open source mist.io doesn't support server monitoring (for now).  So no alerts to receive.

I've also tested MAILER_SETTINGS on settings.py, and set 

```
MAILER_SETTINGS = {
     'mail.host': "my_mail_server",
     'mail.port': "587",
     'mail.tls': True,
     'mail.starttls': True,
     'mail.username': "email",
     'mail.password': "password",
 }
```

then restarted the api container (docker-compose restart api) and then confirm that emails are sent (eg forgot pw, register user etc). Make sure you specify CORE_URI on the same file otherwise all email will contain mist.io server as http://localhost

**Comment by mgogoulos** [comment]
I'll let this open, as the issue seems to be G Suite SMTP settings specific. Changed the title to something more appropriate.
