### ISSUE TITLE
Cannot set Organisation mail alert.

### ISSUE THREAD

**Issue by garelp** [mistio/mist.io#930]
Hello,

Each time I'm trying to put an email in the organisation profile, I get an Internal error and this log error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/usr/lib/python2.7/site-packages/pyramid/router.py", line 161, in handle_request
    response = view_callable(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 586, in __call__
    return view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 319, in attr_view
    return view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 295, in predicate_wrapper
    return view(context, request)
  File "/mist.api/src/mist/api/helpers.py", line 817, in logging_view
    response = func(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 345, in rendered_view
    result = view(context, request)
  File "/usr/lib/python2.7/site-packages/pyramid/config/views.py", line 491, in _requestonly_view
    response = view(request)
  File "/mist.api/src/mist/api/views.py", line 2120, in edit_organization
    from mist.core.methods import update_monitoring_options
ImportError: No module named core.methods

How can I set this email which seems to be the from of the alerting mails???

Thanks.
--
Pierre.

**Comment by d-mo** [comment]
Thank you for reporting this. Keep in mind that the Community Edition of Mist.io does not support monitoring and alerting for the time being. This will change in the upcoming 3.0.0 release which will be out in the coming weeks.

**Comment by garelp** [comment]
Hi,
It wasn't for monitoring but to set the from header for mail. Antispam filter usually drops mail without a proper from:

**Comment by d-mo** [comment]
For that you need to configure the `EMAIL_FROM` param in config/settings.py. Then run `docker-compose restart` for the settings to take effect.

**Comment by garelp** [comment]
Thanks it works 👍
